name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build

      - name: Start server in background
        run: npm run start &

      # - name: Wait for server to be ready
      #   run: npx wait-on http://localhost:3001

      - name: Run Cypress Tests
        run: npm run test-component
