name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 21.x

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6.5.0
        with: 
          install: true
          build: npm run build
          component: true
